### ISSUE TITLE
SMS/USSD features

### ISSUE THREAD

**Issue by nnov4k** [black-roland/homeassistant-gsm-call#1]
hello!  have you any ideas to add a SMS and USSD features for homeassistant-gsm-call ?
add-on locks a gsm-modem port and basic AT commands via SSHCommands cant be used :(

**Comment by black-roland** [comment]
Hey, I'm not confident if this is the case for all modems but there should be multiple interfaces to access the modem. Like:

```
$ ls -1 /dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if0*                                                             
/dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if00-port0
/dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if01-port0
/dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if02-port0
```

I wonder how many interfaces your modem has? Personally, I have one interface configured for this integration and another one is used to receive messages through gammu-smsd — no mutual blocking.

I'd also suggest checking if you have ModemManager enabled as it may also could block the modem interface.

As of SMS support, there is already [an integration for this](https://www.home-assistant.io/integrations/sms/) so I don't think adding SMS support makes sense.

USSD maybe added in the future but there were no such requests until yours. Do you just need to dial USSD to perform some actions (for example, to change tariff options) or is it used to check the account balance?

**Comment by nnov4k** [comment]
Yes, you're right! I've got new ZTE MF180 and all works fine, SMS integration don't blocks calling.
Thank you very much!

**Comment by black-roland** [comment]
> SMS don't connects to 0 port :(

I guess because this interface is blocked by ModemManager. Please try disabling/removing it. By the way, what OS do you use? [Here are instructions for RHEL and Ubuntu](https://askubuntu.com/questions/216114/how-can-i-remove-modem-manager-from-boot/612646).

I had a similar issue with gammu-smsd stopping working after a few hours (SMS integration uses Gammu internally). Issue reproduced even with pure gammu-smsd for SMS receiving only. As in your case, I also had one of the interfaces constantly blocked. Turned out ModemManager was the root cause of all my problems :confused: I guess that might be your case as well, so please try disabling it.

**Comment by nnov4k** [comment]
Thank you for an ideas, i'll try to find a service, which locks a port and report results. I have HassOS installed (jethome d1+ build, based on Debian 11) with no modemmanager within. P.s. we also talks our native language @ your main site :)

**Comment by black-roland** [comment]
Ответил [в комментариях](https://mansmarthome.info/posts/okhrana-doma/sighnalizatsiia-v-home-assistant-s-funktsiiei-dozvona-na-tieliefon/#comments) :slightly_smiling_face:

**Comment by black-roland** [comment]
The issue [seems to be resolved](https://mansmarthome.info/posts/okhrana-doma/sighnalizatsiia-v-home-assistant-s-funktsiiei-dozvona-na-tieliefon/#110). Please reopen if you still have any issues.
